// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_AEL_Rcpp_inner_wrap
Rcpp::List compute_AEL_Rcpp_inner_wrap(Eigen::VectorXd th, Rcpp::Function h, Eigen::VectorXd lam0, double a, Eigen::MatrixXd z, int T);
RcppExport SEXP _VBel_compute_AEL_Rcpp_inner_wrap(SEXP thSEXP, SEXP hSEXP, SEXP lam0SEXP, SEXP aSEXP, SEXP zSEXP, SEXP TSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type th(thSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type h(hSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type lam0(lam0SEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type z(zSEXP);
    Rcpp::traits::input_parameter< int >::type T(TSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_AEL_Rcpp_inner_wrap(th, h, lam0, a, z, T));
    return rcpp_result_gen;
END_RCPP
}
// compute_AEL_Rcpp_inner_prez
Rcpp::List compute_AEL_Rcpp_inner_prez(Eigen::VectorXd th, Eigen::MatrixXd H_Zth, Eigen::VectorXd lam0, double a, Eigen::MatrixXd z, int T);
RcppExport SEXP _VBel_compute_AEL_Rcpp_inner_prez(SEXP thSEXP, SEXP H_ZthSEXP, SEXP lam0SEXP, SEXP aSEXP, SEXP zSEXP, SEXP TSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type th(thSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type H_Zth(H_ZthSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type lam0(lam0SEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type z(zSEXP);
    Rcpp::traits::input_parameter< int >::type T(TSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_AEL_Rcpp_inner_prez(th, H_Zth, lam0, a, z, T));
    return rcpp_result_gen;
END_RCPP
}
// compute_GVA_Rcpp_inner_full
Rcpp::List compute_GVA_Rcpp_inner_full(Eigen::VectorXd mu, Eigen::MatrixXd C, Rcpp::Function h, Rcpp::Function delthh, Rcpp::Function delth_logpi, Eigen::MatrixXd z, Eigen::VectorXd lam0, double rho, double elip, double a, int T_SGD, int T_AEL, int p, int verbosity);
RcppExport SEXP _VBel_compute_GVA_Rcpp_inner_full(SEXP muSEXP, SEXP CSEXP, SEXP hSEXP, SEXP delthhSEXP, SEXP delth_logpiSEXP, SEXP zSEXP, SEXP lam0SEXP, SEXP rhoSEXP, SEXP elipSEXP, SEXP aSEXP, SEXP T_SGDSEXP, SEXP T_AELSEXP, SEXP pSEXP, SEXP verbositySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type mu(muSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type C(CSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type h(hSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type delthh(delthhSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type delth_logpi(delth_logpiSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type z(zSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type lam0(lam0SEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type elip(elipSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type T_SGD(T_SGDSEXP);
    Rcpp::traits::input_parameter< int >::type T_AEL(T_AELSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type verbosity(verbositySEXP);
    rcpp_result_gen = Rcpp::wrap(compute_GVA_Rcpp_inner_full(mu, C, h, delthh, delth_logpi, z, lam0, rho, elip, a, T_SGD, T_AEL, p, verbosity));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_VBel_compute_AEL_Rcpp_inner_wrap", (DL_FUNC) &_VBel_compute_AEL_Rcpp_inner_wrap, 6},
    {"_VBel_compute_AEL_Rcpp_inner_prez", (DL_FUNC) &_VBel_compute_AEL_Rcpp_inner_prez, 6},
    {"_VBel_compute_GVA_Rcpp_inner_full", (DL_FUNC) &_VBel_compute_GVA_Rcpp_inner_full, 14},
    {NULL, NULL, 0}
};

RcppExport void R_init_VBel(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
