# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_lambda_Rcpp <- function(h_list, H_Zth, lam0, a, T, n, d) {
    .Call(`_VBel_compute_lambda_Rcpp`, h_list, H_Zth, lam0, a, T, n, d)
}

compute_AEL_Rcpp_inner <- function(th, h, lam0, a, z, T = 100L) {
    .Call(`_VBel_compute_AEL_Rcpp_inner`, th, h, lam0, a, z, T)
}

compute_AEL_Rcpp_inner_prez <- function(th, H_Zth, lam0, a, z, T = 100L) {
    .Call(`_VBel_compute_AEL_Rcpp_inner_prez`, th, H_Zth, lam0, a, z, T)
}

rcppeigen_hello_world <- function() {
    .Call(`_VBel_rcppeigen_hello_world`)
}

rcppeigen_outerproduct <- function(x) {
    .Call(`_VBel_rcppeigen_outerproduct`, x)
}

rcppeigen_innerproduct <- function(x) {
    .Call(`_VBel_rcppeigen_innerproduct`, x)
}

rcppeigen_bothproducts <- function(x) {
    .Call(`_VBel_rcppeigen_bothproducts`, x)
}

