# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_lambda_Rcpp <- function(h_list, H_Zth, lam0, a, T, n, d) {
    .Call(`_VBel_compute_lambda_Rcpp`, h_list, H_Zth, lam0, a, T, n, d)
}

compute_AEL_Rcpp_inner_wrap <- function(th, h, lam0, a, z, T = 500L) {
    .Call(`_VBel_compute_AEL_Rcpp_inner_wrap`, th, h, lam0, a, z, T)
}

compute_AEL_Rcpp_inner_prez <- function(th, H_Zth, lam0, a, z, T = 500L) {
    .Call(`_VBel_compute_AEL_Rcpp_inner_prez`, th, H_Zth, lam0, a, z, T)
}

compute_GVA_Rcpp_inner_IVtoXII <- function(rho, elip, Egmu, Edelmu, EgC, EdelC, gmu, mu_t, C_t, xi, M, p, i) {
    .Call(`_VBel_compute_GVA_Rcpp_inner_IVtoXII`, rho, elip, Egmu, Edelmu, EgC, EdelC, gmu, mu_t, C_t, xi, M, p, i)
}

compute_GVA_Rcpp_inner_full <- function(mu, C, h, delthh, delth_logpi, z, lam0, rho, elip, a, T, T2, p, verbosity) {
    .Call(`_VBel_compute_GVA_Rcpp_inner_full`, mu, C, h, delthh, delth_logpi, z, lam0, rho, elip, a, T, T2, p, verbosity)
}

